DOMjudge/domjudge-scripts

website/about.shtml, website/chat.shtml, website/header.shtml
As a PR so we can discuss if we should modify what I typed.
=> Replace IRC info with Slack

website/development.shtml
I'm not sure if this will also fix the website directly, but I assume someone else does.
=> Everywhere on the website mailto links are used

make_release.sh
Fixed long lines and quoting issues
=> Shellcheck and bashate fixes

website/index.shtml
As I dont have the self-register server ready yet, this proposal.
=> Test contest

update_demoweb.sh
In the past the file was stashed but local changes were now lost.
I think doing this check is also a good way to autodocument how this should look like. Disadvantage is that a change in the apache.conf.in may now also result in a change in this repo.
=> Explicit fix for demoweb alias

update_demoweb.sh
My last commit also replaced the location of /home/domjudge.
Tested this on the server and I think this should be fine now. Reran update_demoweb and restarted apache2 and the website is still up.
=> Only match the Apache alias

icpc-wf/ansible/domserver.yml, icpc-wf/ansible/files/grafana/my.cnf.j2, icpc-wf/ansible/files/grafana/nginx.conf, icpc-wf/ansible/grafana.yml
Already tested in our demo environment.
=> Small repairs

icpc-wf/ansible/Makefile, icpc-wf/ansible/cds.yml, icpc-wf/ansible/group_vars/all/all.yml, icpc-wf/ansible/group_vars/all/secret.yml.example, icpc-wf/ansible/hosts, icpc-wf/ansible/roles/cds/files/cds.service, icpc-wf/ansible/roles/cds/handlers/main.yml, icpc-wf/ansible/roles/cds/tasks/main.yml, icpc-wf/ansible/roles/cds/templates/cds.conf.j2, icpc-wf/ansible/roles/cds/templates/cdsConfig.xml.j2, icpc-wf/ansible/roles/cds/templates/users.xml.j2
Doing this multiple times for (non WF) contests, I got annoyed and automated it.
=> Add CDS role to Ansible.

icpc-wf/ansible/roles/mysql_server/files/dump-db, icpc-wf/ansible/roles/mysql_server/files/load-db, icpc-wf/ansible/roles/mysql_server/tasks/main.yml
I'm always creating these scripts, so why not do it in Ansible.
=> Add scripts to dump and load database to mysql server role.

icpc-wf/ansible/Makefile, icpc-wf/ansible/hosts, icpc-wf/ansible/mgmt.yml
I think in the future we also want to get all public keys of the current maintainers etc.
=> Monitor the management machine

website/about.shtml
I'll discuss in maintainer if this should be merged.
=> Update maintainerlist from github info

website/demo.shtml
I tried to get the logo there also but it always looked out of place.
=> Notify demoweb users of sentry usage

website/header.shtml
Should these be released on the current day or do we keep the original date?
=> Mention patch release 8.0.1 & 8.1.1

website/tools.shtml
I already wanted to add this yesterday and now also Tobi mentioned it so let's see if we all agree we can prevent the discussion by listing something which can extend while not being maintained by us.
=> List DOMtutor for education

provision-contest/ansible/cds.yml, provision-contest/ansible/files/taillog.desktop.j2, provision-contest/ansible/grafana.yml, provision-contest/ansible/judgehost.yml, provision-contest/ansible/mgmt.yml, provision-contest/ansible/roles/mysql_replication/tasks/main.yml, provision-contest/ansible/scoreboard.yml
Some of the items still in local modifications on the WF test server.
=> Use handlers everywhere v2

provision-contest/ansible/Makefile, provision-contest/ansible/judgehost.yml
As discussed during BAPC, it would be nice to have an option to only deploy the updated code.
=> Add option to deploy code only

provision-contest/ansible/ansible.cfg
For inspiration see:
- https://www.redhat.com/sysadmin/faster-ansible-playbook-execution
- https://raw.githubusercontent.com/ansible/ansible/stable-2.9/examples/ansible.cfg
=> Ansible default behaviour

provision-contest/ansible/EOC/README.md, provision-contest/ansible/EOC/main.yml
The readme contains some explanation on how to use the playbook. Note, this is probably still quite limited, so check the results before relying on them!
=> Adds ansible for end-of-contest procedure.

update_docs.sh
Should we in this case also send an alert in slack?
=> Cleanup docs failure

provision-contest/replay.py
- Allow to remap teams or not
- Use argparse for arguments
- Don't require accounts but use new team_id parameter of submit endpoint
- Add option for internal/external data source
=> Update replay script to be more flexible:

provision-contest/ansible/roles/mysql_server/files/dump-db
Closes: https://github.com/DOMjudge/domjudge-scripts/pull/79
Also related, should this script be moved to the main repo as its also convenient for general usage?
=> Ask for confirmation before overwriting existing DB dump

provision-contest/ansible/roles/mysql_replication/templates/setup-replication.sh.j2
No functional change intended.
=> Fix wording

provision-contest/ansible/judgehost.yml
=> Small unloop

provision-contest/replay.py
Also ignore submissions without ID.
=> Fix skip to submission option for replay script.

provision-contest/ansible/roles/clusterssh/tasks/main.yml
@nickygerritsen why did you not need this when you tested with it?
=> Make sure the clusterssh config dir exists

provision-contest/ansible/roles/mysql_server/files/load-db, provision-contest/ansible/sync_dumps.yml
Also updated the load-db script to allow loading those dumps from alternative locations.
=> Backup dumps of domservers to admin machines

provision-contest/ansible/roles/domserver/templates/nginx-domjudge-inner.j2
See: https://github.com/DOMjudge/domjudge/issues/2654
=> Prevent indexing of DOMjudge instance

provision-contest/ansible/roles/cds/tasks/main.yml
=> added installation of OpenJDK17
