- make_release.sh
These changes are needed to make it possible to deploy a new version via
GitlabCI.
Also fixed some tab/space issues and changed the structure to 4 spaces.
> Restructure to allow CI/CD usage

- cron_tag_release.sh
- make_release.sh
- new_release_howto.md
The last addition to the make_release is not needed anymore as
deployment is now done via the server.
- Setup extra environment variables
- Trigger tests on gitlab
- The server builds the tar.gz is built and signed
- We trigger a pipeline in domjudge-packaging (https://docs.gitlab.com/ee/ci/triggers/#triggering-a-pipeline)
- This can test the build tar.gz, -> Suggested by @eldering to do before triggering
- This can test the debs, -> Seems to react very different
- This can build the dockers -> Manual trigger for now
Unclear:
- Where should the debs be build? -> Probably always manual
TODO:
- Do the website update step (future PR probably)
The reason that I prefer to do as much as possible on gitlab is that the logging in my opinion is easier to follow, but I'm also fine with doing more …
> Cronjob to release on new tags

- cron_tag_release.sh
- make_release.sh
Also directly read the secrets and the removed variable is not used
anymore as this was when the scripts are not available on the server.
> domjudge folder is located in different folder

- contest-api/check-api.sh
- contest-api/json-schema/award.json
- contest-api/json-schema/clarification.json
- contest-api/json-schema/commentaries.json
- contest-api/json-schema/commentary.json
- contest-api/json-schema/common.json
- contest-api/json-schema/contest.json
- contest-api/json-schema/event-feed.json
- contest-api/json-schema/group.json
- contest-api/json-schema/judgement.json
- contest-api/json-schema/language.json
- contest-api/json-schema/organization.json
- contest-api/json-schema/problem.json
- contest-api/json-schema/run.json
- contest-api/json-schema/submission.json
- contest-api/json-schema/team-member.json
- contest-api/json-schema/team.json
These are mostly updates to the JSON schema to make it up to date with the current specification at https://ccs-specs.icpc.io/contest_api. The only things that are (or should be) missing:
- Contest `scoreboard_type` and related changes to other endpoints.
- Any draft changes to the event feed and webhooks.
> Contest api updates

- icpc-wf/ansible/roles/judgedaemon/handlers/main.yml
- icpc-wf/ansible/roles/judgedaemon/tasks/main.yml
- icpc-wf/ansible/roles/judgedaemon/vars/main.yml
Assuming the hyperthreading core is always at the *n*%2==1 core, and the kernel uses cpu(0) this is the next safe bet. The run users are removed as at the WF the judges typicly only run with 1 judgedaemon.
I'll still need to test this, but this is to start the implementation. This closes https://github.com/DOMjudge/domjudge-scripts/issues/15
> Isolate the judge to the 2nd core

- website/download.shtml
DOMjudge releases don't contain a statically compiled
bash/dash shell anymore since 173b380a62b496ec9a47a847
in the main domjudge repo.
The sources directory has been moved under the releases directory
on domjudge.org, since we still need to provide these for older
releases. Just refer to this in the README in releases instead of
on the download page.
> Remove link to sources directory.

- .github/workflows/shellcheck.yml
We now also target against possible other releases and on temporary branches in the project.
> Trigger shellcheck on all PRs

- update_demoweb.sh
I'm not 100% sure this is the only issue, but this does prevent a slow start when the cache is invalid.
> Prewarm cache for first visitor

- icpc-wf/ansible/admin.yml
- icpc-wf/ansible/domserver.yml
- icpc-wf/ansible/group_vars/all/all.yml
- icpc-wf/ansible/hosts
- icpc-wf/ansible/roles/base_packages/tasks/main.yml
- icpc-wf/ansible/roles/domjudge_checkout/tasks/main.yml
Lets first agree on which ones we want to keep and afterwards I can make the message useful.
> Swerc suggestions

- icpc-wf/ansible/roles/judgedaemon/handlers/main.yml
- icpc-wf/ansible/roles/judgedaemon/tasks/main.yml
- icpc-wf/ansible/roles/judgedaemon/templates/domjudge-judgehost.target.j2
Our .service can't be enabled (anymore?) since it does not have a `[Install]` section, but we have a .target for that in the main repo. This templates out this .target file.
cc @edomora97 this is what we talked about yesterday.
> Add judgehost .target systemd file.

- provision-contest/ansible/domserver.yml
- provision-contest/ansible/group_vars/all/secret.yml.example
In most cases we dont do replication and this book will let SQL bind to 0.0.0.0 which is less secure and only relevant when making use of the replication.
> Only make replication an explicit choice

- new_release_howto.md
When we release a version we want to patch any security issues with dependencies. Dependabot will not monitor these branches without explicit telling it to do so.
> Setup dependabot on released version

- website/header.shtml
DOMjudge v8.1.1 was wrongly tagged so missed the Changelog, the v8.1.2 only has the fix for this so the latest version is a proper tarball.
> Mention re-released DOMjudge version

- contest-api/check-api-consistency.php
- contest-api/json-schema/common.json
- contest-api/json-schema/event-feed-array.json
- contest-api/json-schema/legacy-event-feed.json
Some remarks / questions:
*  I'm not a fan of the `endpointssingularcontest` in `common.json` but I'm not sure how to fix that the new feed uses singular `contest`. This also 'bytes' us in the PHP script to check consistency.
* I needed to get rid of `uniqueItems` since the new feed format can have the exact same event twice.
* @eldering mentioned yesterday that he might want to have a branch per spec version, but then we should probably first move this out of this repo? Or we add a flag to denote the version but I'm not sure if that won't get super messy. For now I decided to support both versions, since then our CI will keep working when I open the PR for the new format in the main repo.
> Update check-api script to support new event feed format.

- provision-contest/ansible/mgmt.yml
- provision-contest/ansible/roles/base_packages/tasks/main.yml
I think for the extra packages on the mgmt machine all of these make sense/are useful for our "jumphost"
> Ansible synchronize needs rsync for both client/server

- provision-contest/ansible/roles/domjudge_build/meta/main.yml
- provision-contest/ansible/roles/domjudge_checkout/meta/main.yml
- provision-contest/ansible/roles/domserver/meta/main.yml
- provision-contest/ansible/roles/judgedaemon/meta/main.yml
- provision-contest/ansible/roles/keepalived/meta/main.yml
- provision-contest/ansible/roles/mysql_replication/meta/main.yml
- provision-contest/ansible/roles/phpstorm/meta/main.yml
- provision-contest/ansible/roles/ssh/meta/main.yml
See https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#running-role-dependencies-multiple-times-in-one-play for the reason:
[...] If two roles in a play both list a third role as a dependency, Ansible only runs that role dependency once, unless you pass different parameters, tags, when clause, or use allow_duplicates: true in the role you want to run multiple times. [...]
> Add tags to all dependencies to satisfy Ansible.

- provision-contest/ansible/roles/domjudge_build/handlers/main.yml
- provision-contest/ansible/roles/domjudge_build/tasks/main.yml
- provision-contest/ansible/roles/domserver/tasks/main.yml
- provision-contest/ansible/roles/mysql_server/tasks/main.yml
After testing with the emergency book these fixes where needed. We don't need them in a normal setup (but this should not hurt) as normally the installation of the package also enables these services.
> Emergency unpause fixes

- provision-contest/ansible/Makefile
- provision-contest/ansible/emergency.yml
- provision-contest/ansible/hosts.example
I think in these situations it would be nice if we can already leave and this can just run in the background.
If we would make sure we know which station runs this lockdown we could make it better by doing the shutdown in the make command so all hosts except for the last admin machine are killed with ansible and then the last one stops.
> Add playbooks for emergency situations

- new_release_howto.md
Documenting old releases would make it harder to spot for users that their version is not supported anymore when they still see the docs on our website.
I haven't done this yet for 7.3 + 8.0 but first want to see what the rest thinks of this.
> Remove documentation for unsupported versions

- new_release_howto.md
In theory we can grab this in the job by checking what is the highest semantic version.
The goal of this is to get less messages from snyk/scout that we have packages with a problem in them.
> Mention the automatic job to rebuild the docker containers

- .github/workflows/shellcheck.yml
See
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/ and
https://github.com/actions/checkout/issues/1047
> Upgrade shellcheck checkout to make it work again.

- provision-contest/disable-turboboost_ht
This results in a slightly easier to understand outcome.
On CPUs like where there are 8+8 cores with hyperthreading and cpu0 is on the same core as cpu9, cpu1 and cpu10 etc. Since the script went through cpus lexicographically, it did traverse cpu 10-15 before doing 2-9. This resulted in disabling cpus 2-9, while cpu0, cpu1 and cpu 10-15 were online which is very confusing.
Now it sorts things numerically, so goes through them in a more predictable order and the results is more predictable: in this particular case, cpu 0-7 are online, and cpu 8-15 are disabled.
In more general words: the cpu with the lowest number of each core is still online, higher numbers are disabled.
> Sort CPUs/cores in disable turboboost script numerically.

- provision-contest/disable-turboboost_ht
In multi-cpu machines the script used to disable (most of) the second physical cpu. This is since the `core_id` numbering is seperate for every physical cpu. In a 8+8 layout the `core_id` is in the range of 0-7.
Since the script only checked whether it had seen a core-id it will disable the entire second physical cpu. By adding the `physical_package_id` this problem is eliminated.
> Extend key with physical_package_id

- provision-contest/replay.py
Also do a minor fix to always prepend single digit minutes/seconds with 0s.
> Add simulation speed as option to the replay script.

- website/demo.shtml
I can't test this locally but `<code>` should still be valid HTML5.
> Document the API doc on the website

- provision-contest/ansible/group_vars/all/all.yml.example
- provision-contest/ansible/roles/judgedaemon/tasks/main.yml
This is also a good example for people on Digital Ocean etc.
I think we actually need neither of those extra kernel options but leaving the machine similar to how we got it should lead to a more stable (or easier to debug) machine.
> Configure judgehost on AWS

- provision-contest/ansible/group_vars/all/secret.yml.example
- provision-contest/ansible/roles/domserver/tasks/main.yml
As we use our contests to test `main` most of the time we should gather all encountered errors often, this makes this a bit easier.
> Allow setting the SENTRY_DNS

- provision-contest/replay.py
- Check problem IDs.
- Check contest data.
- Allow to completely randomize team IDs.
- Unify some error output.
> Improvements to replay script:

- provision-contest/ansible/admin.yml
- provision-contest/ansible/domserver.yml
- provision-contest/ansible/group_vars/all/all.yml.example
- provision-contest/ansible/roles/cds/files/cds.service
- provision-contest/ansible/roles/clusterssh/tasks/main.yml
- provision-contest/ansible/roles/clusterssh/templates/clusters.j2
- provision-contest/ansible/roles/hosts/templates/hosts.j2
- provision-contest/ansible/roles/keepalived/templates/keepalived.conf.j2
- provision-contest/ansible/roles/mysql_replication/tasks/main.yml
- provision-contest/ansible/roles/mysql_replication/templates/mysql.replication.cnf.j2
- provision-contest/ansible/roles/mysql_replication/templates/setup-replication.sh.j2
Mostly things which were fixed for Luxor + one opinionated fix.
> Wfluxor findings

- provision-contest/ansible/roles/base_packages/defaults/main.yml
- provision-contest/ansible/roles/domserver/defaults/main.yml
We only need those on the domservers (& admin machines).
> Don't install texlive on judgehosts

- provision-contest/ansible/group_vars/all/secret.yml.example
The replication password is set lower in the wf46/wf47 as besides the risk for leaking the database we would also setup replication on the analyst instance.
The ICPC-tools variables are not relevant here as we at this point don't setup the CDS.
> Remove unneeded variables

- domlogo/domlogo.py
> Make domlogo more robust when images are missing or folders not created

- provision-contest/ansible/Makefile
- provision-contest/ansible/roles/grafana/templates/prometheus.yml.j2
- provision-contest/ansible/roles/prometheus_target_all/handlers/main.yml
- provision-contest/ansible/roles/prometheus_target_all/tasks/main.yml
- provision-contest/ansible/roles/prometheus_target_web/meta/main.yml
- provision-contest/ansible/roles/prometheus_target_web/tasks/main.yml
This is not possible (yet) for php_fpm but that one also exposes the least interesting metrics for people snooping. If we would want that we would need to do something with nginx for this.
This is relevant for the online judge but also makes sense as teams can always query the node endpoint on domservers.
> Use encrypt nginx/mariadb/node exporter traffic

- provision-contest/ansible/roles/keepalived/templates/keepalived.conf.j2
This both prevents/fixes some security alerts and also makes sure that the files that the alerting script copies are the right ones.
> Run keepalived notification scripts as domjudge user

- provision-contest/ansible/roles/keepalived/files/alerting/bin/alerting.sh.template
- provision-contest/ansible/roles/keepalived/files/alerting/bin/trigger_alert.sh
- provision-contest/ansible/roles/keepalived/tasks/main.yml
At the ICPC WFs in Egypt the correct sound card to use is 0; just try to set the volume on both 0 and 1. Also try beep and send a desktop notification.
> Improve keepalived alert script and add some comments

- provision-contest/ansible/roles/ssh/files/config
This allows both making local changes that do not get overwritten and still distributing changes via ansible.
Note that ideally any specific additions should be done above the include, so that the local snippet can override them.
> Include local config snippet from SSH config

- provision-contest/ansible/roles/base_packages/defaults/main.yml
- provision-contest/ansible/roles/system_fixes/tasks/main.yml
This automatically logs all changes made to /etc in git and is useful for debugging purposes, while it doesn't hurt.
> Install etckeeper and run hourly

- update_demoweb.sh
This was also fixed in the crontab on domjudge.org for various commands. The composer file is now in the webapp folder in the main repo.
> Fix demoweb installation with new composer location

- provision-contest/ansible/Makefile
- provision-contest/ansible/roles/domjudge_checkout/tasks/main.yml
This requires a new way of creating the archive, in the past vendor was the only thing of reasonable size in lib, for webapp we have other files there also. For now we should just archive the vendor only from within webapp.
> The vendor dir was moved in main

- provision-contest/ansible/roles/keepalived/templates/keepalived.conf.j2
We use the MySQL replication and keepalived together, if we ever have a usecase where we want to replicate the database and IP in a different way we can set that later.
I think even for the setup:
dj-primary: desktop
dj-second: desktop
dj-emerg: laptop
we would still prefer 1 variable and just not set the priority for dj-emerg so that it wouldn't start `keepalived` but would be setup with replication.
> Simplify variables to be set

- provision-contest/ansible/README.md
- provision-contest/ansible/roles/domjudge_checkout/files/.gitignore
Also removed it from version control as we need to create it every year and have multiple other binaries which we don't version control.
> Document the vendor snapshot

- provision-contest/ansible/roles/base_packages/tasks/main.yml
This would make the first installation slower and if the `packages` are updated during the WFs we probably want to explicit do the update and see what gets changed.
> Don't upgrade packages with ansible

- provision-contest/ansible/group_vars/onprem/all.yml.example
- provision-contest/ansible/group_vars/onprem/analyst-domserver
- provision-contest/ansible/group_vars/onprem/analyst-judgehost
- provision-contest/ansible/group_vars/onprem/analyst/secret.yml.example
- provision-contest/ansible/group_vars/onprem/secret.yml.example
- provision-contest/ansible/group_vars/onprem/wfinal-domserver
- provision-contest/ansible/group_vars/onprem/wfinal-judgehost
- provision-contest/ansible/group_vars/onprem/wfinal/secret.yml.example
- provision-contest/ansible/hosts
See Pat's list, I'm not sure about the analyst instance if that is the host `green` or the host `analyst-green`, went with the `analyst-green`.
Onsite we should discuss which machine will be dualhomed or which firewall can be changed so we can manage the analyst instance.
This also requires a split in grouping to make sure that the analyst instance doesn't get a replication setup. It wouldn't hurt but its better to not install extras which are not needed as it opens up the sql server there in green.
> Set DOMserver IPs

- provision-contest/ansible/roles/judgedaemon/tasks/main.yml
Also install kotlin as we always do this for our own contests.
This does require https://github.com/DOMjudge/domjudge/pull/2679 to get merged also.
> Use the host repositories on setups we install

- provision-contest/ansible/admin.yml
Closes: https://github.com/DOMjudge/domjudge-scripts/issues/152
> Multiple remotes

- provision-contest/ansible/roles/clusterssh/files/tmux-cssh
- provision-contest/ansible/roles/clusterssh/tasks/main.yml
- provision-contest/ansible/roles/clusterssh/templates/tmux-cluster.sh.j2
I can't find if there is an extra config but that can be easily added if @tuupke / @meisterT has such a thing.
> Add tmux-cssh as replacement for clusterssh

- provision-contest/ansible/roles/judgedaemon/tasks/main.yml
In the past we could (and did) fail somewhere in the playbook which would result in not handling this notified handler. This also meant that we would not copy the file again on the next run, so didn't kick the handler and also didn't hit the handler on the next run.
The disadvantage here is we might hit other handlers more often if next roles want to hit the same handler.
> Make sure tune_cpu gets started

- provision-contest/ansible/group_vars/domserver.yml
- provision-contest/ansible/roles/domserver/templates/nginx-domjudge-inner.j2
In our setup, we need to configure the proxy for IP autologin.
@vmcj As this is only relevant for domserver, I suggest adding a new `group_vars` file instead of cluttering `all`. What do you think?
> Add option to configure NGINX real ip

- provision-contest/disable-turboboost_ht
Also clarified the package/socket as package is more correct but socket is better known and fixed a typo.
This does not fix our issue yet but will most likely help us a bit more.
> Disable efficiency cores
